import os
import re
import shutil
import subprocess
import sys
import time
from typing import Any, Optional

from .core_utils import logger


class EvolutionMixin:
    """Methods for project analysis, verification, and git librarian duties."""

    target_dir: str
    analysis_path: str
    history_path: str
    symbols_path: str
    llm_engine: object
    code_parser: object
    ledger: dict[str, Any]
    key_cooldowns: dict
    manual_target_file: Optional[str]

    def handle_git_librarian(self, rel_path: str, iteration: int):
        """Creates a branch, generates an AI summary, and opens a professional PR."""
        if not os.path.exists(os.path.join(self.target_dir, ".git")):
            return

        # 1. Capture the raw diff before committing
        diff_proc = subprocess.run(
            ["git", "diff", "HEAD", rel_path],
            cwd=self.target_dir,
            capture_output=True,
            text=True,
        )
        diff_text = diff_proc.stdout or "Minor structural refinement."

        # 2. Ask the AI to write the PR summary (inherited from CoreUtilsMixin)
        summary = self.generate_pr_summary(rel_path, diff_text)
        title = summary.get("title", f"Evolution: Refactor of {rel_path}")
        body = summary.get(
            "body",
            f"This PR was automatically generated by PyOB.\n\nFile: `{rel_path}`",
        )

        # 3. Git Operations
        timestamp = int(time.time())
        branch_name = f"pyob-evolution-v{iteration}-{timestamp}"
        logger.info(f" LIBRARIAN: Publishing Evolution: {title}")

        if not self._run_git_command(["git", "checkout", "-b", branch_name]):
            return

        self._run_git_command(["git", "add", "--update"])

        # Use AI-generated title as commit message
        if not self._run_git_command(["git", "commit", "-m", title]):
            return

        # 4. Push to GitHub and create the PR
        if shutil.which("gh"):
            logger.info("Pushing to GitHub and opening Pull Request...")
            if self._run_git_command(["git", "push", "origin", branch_name]):
                base_branch = getattr(self, "last_branch_name", "main")
                self._run_git_command(
                    [
                        "gh",
                        "pr",
                        "create",
                        "--title",
                        title,
                        "--body",
                        body,
                        "--base",
                        base_branch,
                    ]
                )
                self.last_branch_name = branch_name
                # Increment the session counter only after successful PR creation
                if hasattr(self, "session_pr_count"):
                    self.session_pr_count += 1
                    logger.info(
                        f"Session Progress: {self.session_pr_count}/8 PRs completed."
                    )
        else:
            logger.warning("GitHub CLI (gh) not found. Committed locally only.")

    def _run_final_verification_and_heal(self, backup_state: dict) -> bool:
        """Runs the project entry file for 10 seconds and auto-fixes crashes."""
        entry_file = self.llm_engine._find_entry_file()
        if not entry_file:
            logger.warning("No main entry file found. Skipping runtime test.")
            return True

        rel_entry_file = os.path.relpath(entry_file, self.target_dir)

        for attempt in range(3):
            logger.info(f"Launching `{rel_entry_file}` (Attempt {attempt + 1}/3)")
            cmd: list[str] = []
            is_html = entry_file.endswith((".html", ".htm"))
            is_py = entry_file.endswith(".py")
            is_js = entry_file.endswith((".js", "package.json"))

            if is_py:
                venv_py = os.path.join(self.target_dir, "build_env", "bin", "python3")
                python_cmd = venv_py if os.path.exists(venv_py) else sys.executable
                cmd = [python_cmd, entry_file]
            elif is_js:
                cmd = (
                    ["npm", "start"]
                    if entry_file.endswith("package.json")
                    else ["node", entry_file]
                )
            elif is_html:
                if os.environ.get("GITHUB_ACTIONS") == "true":
                    return True
                if sys.platform == "darwin":
                    cmd = ["open", entry_file]
                elif sys.platform == "win32":
                    cmd = [f'start "" "{entry_file}"']
                else:
                    cmd = ["xdg-open", entry_file]

            if not cmd:
                return True
            use_shell = bool(cmd and (cmd[0].startswith("start") or cmd[0] == "open"))

            start_time = time.time()
            stdout, stderr = "", ""
            process: Optional[subprocess.Popen[str]] = None
            timeout_val = 5 if is_html else 10

            try:
                process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    cwd=self.target_dir,
                    shell=use_shell,
                )
                try:
                    stdout, stderr = process.communicate(timeout=timeout_val)
                except subprocess.TimeoutExpired as e:
                    # Capture the standard output/error buffers accumulated before timeout
                    stdout = e.stdout or ""
                    stderr = e.stderr or ""

                    # Clean up the process to release ports and prevent socket leaks
                    process.terminate()
                    try:
                        process.wait(timeout=2)
                    except subprocess.TimeoutExpired:
                        process.kill()
                        process.wait()

                    # For long-running servers, a timeout with no error keywords is a SUCCESS
                    has_error = any(
                        kw in stderr or kw in stdout
                        for kw in [
                            "Traceback",
                            "Exception",
                            "Error:",
                            "ModuleNotFoundError",
                            "ImportError",
                        ]
                    )
                    if not has_error:
                        logger.info(
                            f"App ran successfully for {timeout_val}s (timeout reached without errors)."
                        )
                        return True
            except Exception as e:
                logger.error(f"Execution failed: {e}")
                stdout, stderr = "", str(e)

            duration = time.time() - start_time
            has_error = any(
                kw in stderr or kw in stdout
                for kw in [
                    "Traceback",
                    "Exception",
                    "Error:",
                    "ModuleNotFoundError",
                    "ImportError",
                ]
            )
            if process and process.returncode not in (0, 15, -15, None) or has_error:
                logger.warning(f"App crashed after {duration:.1f}s!")
                if attempt < 2:
                    self.llm_engine._fix_runtime_errors(
                        stderr + "\n" + stdout, entry_file
                    )
            else:
                logger.info(f"App ran successfully for {duration:.1f}s.")
                return True

        self.llm_engine.restore_workspace(backup_state)
        return False

    def pick_target_file(self) -> str:
        """Uses LLM to strategically pick the next file to evolve."""
        # Fix: Cast manual_target_file to Optional[str] via local variable for Mypy
        manual: Optional[str] = getattr(self, "manual_target_file", None)
        if manual:
            setattr(self, "manual_target_file", None)
            return str(manual)

        analysis = str(self._read_file(self.analysis_path))
        history = str(self._read_file(self.history_path) or "No history yet.")
        last_file = ""
        for line in reversed(history.strip().split("\n")):
            if line.startswith("## "):
                match = re.search(r"`([^`]+)`", line)
                if match:
                    last_file = match.group(1)
                    break

        hotspots_text = ""
        try:
            hotspot_proc = subprocess.run(
                ["git", "log", "--format=", "--name-only"],
                cwd=self.target_dir,
                capture_output=True,
                text=True,
            )
            from collections import Counter

            counts = Counter([f for f in hotspot_proc.stdout.splitlines() if f.strip()])
            top_hotspots = [f for f, _ in counts.most_common(5)]
            if top_hotspots:
                hotspots_text = (
                    "### Git Hotspots (frequently changed):\n"
                    + "\n".join(f"- {f}" for f in top_hotspots)
                    + "\n\n"
                )
        except Exception:
            pass

        # Build an authoritative list of files that actually exist in the repo.
        try:
            from pyob.core_utils import IGNORE_DIRS, IGNORE_FILES, SUPPORTED_EXTENSIONS

            real_files = []
            for root, dirs, files in os.walk(self.target_dir):
                # Prune ignored and hidden directories in-place to prevent traversing them
                dirs[:] = [
                    d for d in dirs if d not in IGNORE_DIRS and not d.startswith(".")
                ]
                for fname in files:
                    rel_path = os.path.relpath(
                        os.path.join(root, fname), self.target_dir
                    )
                    path_parts = rel_path.split(os.sep)

                    # Skip hidden files/dirs
                    if any(part.startswith(".") for part in path_parts):
                        continue

                    # Skip ignored directories
                    if any(part in IGNORE_DIRS for part in path_parts):
                        continue

                    # Skip ignored files (like brain.json)
                    if fname in IGNORE_FILES:
                        continue

                    # Only include supported extensions
                    if not any(fname.endswith(ext) for ext in SUPPORTED_EXTENSIONS):
                        continue

                    real_files.append(rel_path)

            real_files.sort()
        except Exception:
            real_files = []

        real_files_text = (
            "### AVAILABLE FILES (you MUST pick from this exact list ONLY):\n"
            + "\n".join(f"- {f}" for f in real_files)
            + "\n\n"
            if real_files
            else ""
        )

        prompt = (
            f"Choose ONE relative file path to review next based on ANALYSIS.md/HISTORY.md.\n"
            f"CRITICAL RULES:\n"
            f"1. You MUST pick a file from the AVAILABLE FILES list below. Do NOT invent filenames.\n"
            f"2. DO NOT pick `{last_file}`.\n"
            f"3. Rotate between logic, UI, and styles.\n"
            f"4. Prioritize files that are highly complex or frequently changed.\n"
            f"Output ONLY the exact relative path as it appears in the AVAILABLE FILES list.\n\n"
            f"{real_files_text}"
            f"### Analysis:\n{analysis}\n### History:\n{history}\n{hotspots_text}"
        )

        def val(text: str) -> bool:
            path = self._extract_path_from_llm_response(text)
            return (
                os.path.exists(os.path.join(self.target_dir, path))
                and path != last_file
            )

        response = self.get_valid_llm_response(prompt, val, context="Target Selector")

        return str(self._extract_path_from_llm_response(response))

    def build_initial_analysis(self):
        """Bootstraps ANALYSIS.md and SYMBOLS.json."""
        logger.info("ANALYSIS.md not found. Bootstrapping Deep Symbolic Scan...")
        all_files = sorted(self.llm_engine.scan_directory())
        struct_map = "\n".join(os.path.relpath(f, self.target_dir) for f in all_files)

        p_summary = self.get_valid_llm_response(
            f"Write a 2-sentence summary of this project: {struct_map}",
            lambda t: len(t) > 5,
            context="Project Genesis",
        ).strip()
        content = f"# Project Analysis\n\n**Project Summary:**\n{p_summary}\n\n-----\n## File Directory\n\n"

        file_structures = {}
        for f_path in all_files:
            rel = os.path.relpath(f_path, self.target_dir)
            with open(f_path, "r", encoding="utf-8", errors="ignore") as f:
                code = f.read()
            self.update_ledger_for_file(rel, code)
            file_structures[rel] = self.code_parser.generate_structure_dropdowns(
                f_path, code
            )

        batch_prompt = "Output 'filepath: summary' for each:\n" + "\n".join(
            f"{r}: {s}" for r, s in file_structures.items()
        )
        batch_resp = self.get_valid_llm_response(
            batch_prompt, lambda t: ":" in t, context="Batch Genesis"
        ).strip()

        summaries = {
            line.split(":", 1)[0].strip("`* "): line.split(":", 1)[1].strip()
            for line in batch_resp.splitlines()
            if ":" in line
        }

        for f_path in all_files:
            rel = os.path.relpath(f_path, self.target_dir)
            summary_text = summaries.get(rel, "No summary.")
            content += f"### `{rel}`\n**Summary:** {summary_text}\n\n{file_structures[rel]}\n---\n"

        with open(self.analysis_path, "w", encoding="utf-8") as f:
            f.write(content)
        self.save_ledger()

    def wrap_up_evolution_session(self):
        """Generates a master summary of the entire session and opens a final PR."""
        logger.info("🎬 INITIATING WRAP-UP PHASE: Generating session summary...")

        history_text = self._read_file(self.history_path)

        prompt = f"""
        Analyze the following evolution history for this session and write a 'Master Session Summary'.
        We have successfully submitted {self.session_pr_count} Pull Requests.
        YOUR TASK:
        Create a Markdown report named 'PR_SUMMARY.md'.
        Include:
        1. ## Session Overview (High-level goals achieved)
        2. ## Technical Milestones (List the major features/refactors)
        3. ## Architectural Impact (How the codebase is healthier now)
        HISTORY:
        {history_text}
        Output ONLY the Markdown content for the file. Use a professional, triumphant tone.
        """
        summary_md = self.get_valid_llm_response(
            prompt, lambda t: len(t) > 100, context="Session Architect"
        )
        # Save the file to root
        summary_path = os.path.join(self.target_dir, "PR_SUMMARY.md")
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write(summary_md)

        # Create a final branch for the summary
        branch_name = f"evolution-summary-{int(time.time())}"
        self._run_git_command(["git", "checkout", "-b", branch_name])
        self._run_git_command(["git", "add", "PR_SUMMARY.md"])
        self._run_git_command(
            ["git", "commit", "-m", "Final: Evolution Session Summary Report"]
        )

        if shutil.which("gh"):
            self._run_git_command(["git", "push", "origin", branch_name])
            self._run_git_command(
                [
                    "gh",
                    "pr",
                    "create",
                    "--title",
                    f"🏆 Final Evolution Summary: {self.session_pr_count} PRs Completed",
                    "--body",
                    "This PR contains the architectural summary for the entire autonomous run. PyOB has completed its assigned tasks and is now entering sleep mode.",
                    "--base",
                    "main",
                ]
            )

        logger.info("✅ Final summary submitted. PyOB is now resting.")
