import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from typing import Callable, Any, Optional

from .core_utils import logger


class EvolutionMixin:
    """Methods for project analysis, verification, and git librarian duties."""
    target_dir: str
    analysis_path: str
    history_path: str
    symbols_path: str
    llm_engine: Any
    code_parser: Any
    ledger: dict
    key_cooldowns: dict
    manual_target_file: Optional[str]

    def handle_git_librarian(self, rel_path: str, iteration: int):
        """Creates a branch, generates an AI summary, and opens a professional PR."""
        if not os.path.exists(os.path.join(self.target_dir, ".git")):
            return

        diff_proc = subprocess.run(
            ["git", "diff", "HEAD", rel_path],
            cwd=self.target_dir,
            capture_output=True,
            text=True,
        )
        diff_text = diff_proc.stdout or "Minor structural refinement."

        # generate_pr_summary is inherited from CoreUtilsMixin
        summary = getattr(self, "generate_pr_summary")(rel_path, diff_text)
        title = summary.get("title", f"Evolution: Refactor of {rel_path}")
        body = summary.get(
            "body",
            f"This PR was automatically generated by PyOB.\n\nFile: `{rel_path}`",
        )

        timestamp = int(time.time())
        branch_name = f"pyob-evolution-v{iteration}-{timestamp}"
        logger.info(f" LIBRARIAN: Publishing Evolution: {title}")

        if not getattr(self, "_run_git_command")(["git", "checkout", "-b", branch_name]):
            return
        getattr(self, "_run_git_command")(["git", "add", rel_path])
        if not getattr(self, "_run_git_command")(["git", "commit", "-m", title]):
            return

        if shutil.which("gh"):
            logger.info("Pushing to GitHub and opening Pull Request...")
            if getattr(self, "_run_git_command")(["git", "push", "origin", branch_name]):
                getattr(self, "_run_git_command")(
                    [
                        "gh",
                        "pr",
                        "create",
                        "--title",
                        title,
                        "--body",
                        body,
                        "--base",
                        "main",
                    ]
                )
        else:
            logger.warning("GitHub CLI (gh) not found. Committed locally only.")

    def _run_final_verification_and_heal(self, backup_state: dict) -> bool:
        """Runs the project entry file for 10 seconds and auto-fixes crashes."""
        entry_file = self.llm_engine._find_entry_file()
        if not entry_file:
            logger.warning("No main entry file found. Skipping runtime test.")
            return True

        rel_entry_file = os.path.relpath(entry_file, self.target_dir)

        for attempt in range(3):
            logger.info(f"Launching `{rel_entry_file}` (Attempt {attempt + 1}/3)")
            cmd: list[str] = []
            is_html = entry_file.endswith((".html", ".htm"))
            is_py = entry_file.endswith(".py")
            is_js = entry_file.endswith((".js", "package.json"))

            if is_py:
                venv_py = os.path.join(self.target_dir, "build_env", "bin", "python3")
                python_cmd = venv_py if os.path.exists(venv_py) else sys.executable
                cmd = [python_cmd, entry_file]
            elif is_js:
                cmd = (
                    ["npm", "start"]
                    if entry_file.endswith("package.json")
                    else ["node", entry_file]
                )
            elif is_html:
                if os.environ.get("GITHUB_ACTIONS") == "true":
                    return True
                if sys.platform == "darwin":
                    cmd = ["open", entry_file]
                elif sys.platform == "win32":
                    cmd = [f'start "" "{entry_file}"']
                else:
                    cmd = ["xdg-open", entry_file]

            if not cmd:
                return True
            use_shell = bool(cmd and (cmd[0].startswith("start") or cmd[0] == "open"))

            start_time = time.time()
            try:
                process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    cwd=self.target_dir,
                    shell=use_shell,
                )
                if is_html:
                    try:
                        stdout, stderr = process.communicate(timeout=5)
                        if process.returncode == 0:
                            return True
                    except subprocess.TimeoutExpired:
                        process.terminate()
                        process.wait()
                        return True
                stdout, stderr = process.communicate(timeout=10)
            except Exception as e:
                logger.error(f"Execution failed: {e}")
                stdout, stderr = "", str(e)

            duration = time.time() - start_time
            has_error = any(
                kw in stderr or kw in stdout
                for kw in [
                    "Traceback",
                    "Exception",
                    "Error:",
                    "ModuleNotFoundError",
                    "ImportError",
                ]
            )
            if process.returncode not in (0, 15, -15, None) or has_error:
                logger.warning(f"App crashed after {duration:.1f}s!")
                if attempt < 2:
                    self.llm_engine._fix_runtime_errors(
                        stderr + "\n" + stdout, entry_file
                    )
            else:
                logger.info(f"App ran successfully for {duration:.1f}s.")
                return True

        self.llm_engine.restore_workspace(backup_state)
        return False

    def pick_target_file(self) -> str:
        """Uses LLM to strategically pick the next file to evolve."""
        # Fix: Cast manual_target_file to Optional[str] via local variable for Mypy
        manual: Optional[str] = getattr(self, "manual_target_file", None)
        if manual:
            setattr(self, "manual_target_file", None)
            return str(manual)

        analysis = str(getattr(self, "_read_file")(self.analysis_path))
        history = str(
            getattr(self, "_read_file")(self.history_path) or "No history yet."
        )
        last_file = ""
        for line in reversed(history.strip().split("\n")):
            if line.startswith("## "):
                match = re.search(r"`([^`]+)`", line)
                if match:
                    last_file = match.group(1)
                    break

        prompt = (
            f"Choose ONE relative file path to review next based on ANALYSIS.md/HISTORY.md.\n"
            f"STRATEGIC RULES:\n1. DO NOT pick `{last_file}`.\n"
            f"2. Rotate between logic, UI, and styles.\nOutput ONLY the path.\n\n"
            f"### Analysis:\n{analysis}\n### History:\n{history}"
        )

        def val(text: str) -> bool:
            path = getattr(self, "_extract_path_from_llm_response")(text)
            return (
                os.path.exists(os.path.join(self.target_dir, path))
                and path != last_file
            )

        response = getattr(self, "get_valid_llm_response")(
            prompt, val, context="Target Selector"
        )
        # Fix: Explicitly return a string
        return str(getattr(self, "_extract_path_from_llm_response")(response))

    def build_initial_analysis(self):
        """Bootstraps ANALYSIS.md and SYMBOLS.json."""
        logger.info("ANALYSIS.md not found. Bootstrapping Deep Symbolic Scan...")
        all_files = sorted(self.llm_engine.scan_directory())
        struct_map = "\n".join(os.path.relpath(f, self.target_dir) for f in all_files)

        p_summary = getattr(self, "get_valid_llm_response")(
            f"Write a 2-sentence summary of this project: {struct_map}",
            lambda t: len(t) > 5,
            context="Project Genesis",
        ).strip()
        content = f"# Project Analysis\n\n**Project Summary:**\n{p_summary}\n\n-----n\n## File Directory\n\n"

        file_structures = {}
        for f_path in all_files:
            rel = os.path.relpath(f_path, self.target_dir)
            with open(f_path, "r", encoding="utf-8", errors="ignore") as f:
                code = f.read()
            self.update_ledger_for_file(rel, code)
            file_structures[rel] = self.code_parser.generate_structure_dropdowns(
                f_path, code
            )

        batch_prompt = "Output 'filepath: summary' for each:\n" + "\n".join(
            f"{r}: {s}" for r, s in file_structures.items()
        )
        batch_resp = getattr(self, "get_valid_llm_response")(
            batch_prompt, lambda t: ":" in t, context="Batch Genesis"
        ).strip()

        summaries = {
            line.split(":", 1)[0].strip("`* "): line.split(":", 1)[1].strip()
            for line in batch_resp.splitlines()
            if ":" in line
        }

        for f_path in all_files:
            rel = os.path.relpath(f_path, self.target_dir)
            summary_text = summaries.get(rel, "No summary.")
            content += f"### `{rel}`\n**Summary:** {summary_text}\n\n{file_structures[rel]}\n---\n"

        with open(self.analysis_path, "w", encoding="utf-8") as f:
            f.write(content)
        self.save_ledger()
