import os
import re

from .core_utils import (
    FEATURE_FILE_NAME,
    PR_FILE_NAME,
    logger,
)


class FeatureOperationsMixin:
    target_dir: str
    pr_file: str
    feature_file: str
    session_context: list[str]

    def write_pr(self, filepath: str, explanation: str, llm_response: str):
        rel_path = os.path.relpath(filepath, self.target_dir)
        mode = "a" if os.path.exists(self.pr_file) else "w"
        with open(self.pr_file, mode, encoding="utf-8") as f:
            if mode == "w":
                f.write(
                    "# Autonomous Code Review & Patch Proposals\n\n*Automatically generated by AutoPR Reviewer*\n\n---\n"
                )
            f.write(
                f"\n## Review for `{rel_path}`\n**AI Analysis & Fixes:**\n{explanation}\n\n"
            )
            edits = re.findall(
                r"<EDIT>.*?</EDIT>", llm_response, re.DOTALL | re.IGNORECASE
            )
            if edits:
                f.write("### Proposed Patch:\n```xml\n")
                for edit in edits:
                    f.write(edit.strip() + "\n\n")
                f.write("```\n")
            f.write("\n---\n")
        logger.info(f"Appended successful fix for {rel_path} to {PR_FILE_NAME}")

    def analyze_file(self, filepath: str, current_index: int, total_files: int):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                lines = f.readlines()
                content = "".join(lines)
        except UnicodeDecodeError:
            return
        lang_name, lang_tag = getattr(self, "get_language_info")(filepath)
        filename = os.path.basename(filepath)
        logger.info(
            f"[{current_index}/{total_files}] Scanning {filename} ({lang_name}) - Reading {len(lines)} lines into AI context..."
        )
        ruff_out, mypy_out, custom_issues = "", "", []
        if lang_tag == "python":
            ruff_out, mypy_out = getattr(self, "run_linters")(filepath)
            custom_issues = getattr(self, "scan_for_lazy_code")(filepath, content)
        prompt = getattr(self, "build_patch_prompt")(
            lang_name, lang_tag, content, ruff_out, mypy_out, custom_issues
        )
        new_code, explanation, llm_response = getattr(self, "get_valid_edit")(
            prompt, content, require_edit=False, target_filepath=filepath
        )
        if new_code == content:
            logger.info(f"AI Analysis complete. No changes required for {filename}.\n")
            return
        if new_code != content:
            self.write_pr(filepath, explanation, llm_response)
            self.session_context.append(
                f"Proposed patch for `{filename}` to fix: {explanation}"
            )
            logger.info(
                f" Issues found and patched in {filename}. Added to {PR_FILE_NAME}.\n"
            )

    def propose_feature(self, target_path: str):
        rel_path = os.path.relpath(target_path, self.target_dir)
        lang_name, lang_tag = getattr(self, "get_language_info")(target_path)
        with open(target_path, "r", encoding="utf-8") as f:
            content = f.read()
        logger.info(
            f"\nPHASE 2: Generating an interactive feature proposal for [{rel_path}]..."
        )
        memory_section = getattr(self, "_get_rich_context")()
        prompt = getattr(self, "load_prompt")(
            "PF.md",
            lang_name=lang_name,
            memory_section=memory_section,
            lang_tag=lang_tag,
            content=content,
            rel_path=rel_path,
        )
        print("\n" + "=" * 50)
        print(f" Feature Proposal Prompt Ready: [{rel_path}]")
        print("=" * 50)
        print(
            f"The AI has prepared a prompt to generate a feature proposal for: {rel_path}"
        )
        user_choice = getattr(self, "get_user_approval")(
            "Hit ENTER to send as-is, type 'EDIT_PROMPT' to refine the full prompt, 'AUGMENT_PROMPT' to add quick instructions, or 'SKIP' to cancel this proposal.",
            timeout=220,
        )
        if user_choice == "SKIP":
            logger.info("Feature proposal skipped by user.")
            return
        if user_choice == "EDIT_PROMPT":
            prompt = getattr(self, "_edit_prompt_with_external_editor")(prompt)
            if not prompt.strip():
                logger.warning("Edited prompt is empty. Skipping feature proposal.")
                return
        elif user_choice == "AUGMENT_PROMPT":
            logger.info("Opening augmentation editor to add quick instructions...")
            augmentation_text = getattr(self, "_get_user_prompt_augmentation")()
            if augmentation_text.strip():
                prompt += f"\n\n### User Augmentation:\n{augmentation_text.strip()}"
                logger.info("Prompt augmented with user input for feature proposal.")
            else:
                logger.info("No augmentation provided.")

        def validator(text):
            return "<SNIPPET>" in text and "</SNIPPET>" in text

        llm_response = getattr(self, "get_valid_llm_response")(
            prompt, validator, context=rel_path
        )
        thought_match = re.search(
            r"<(?:THOUGHT|EXPLANATION)>(.*?)</(?:THOUGHT|EXPLANATION)>",
            llm_response,
            re.DOTALL | re.IGNORECASE,
        )
        snippet_match = re.search(
            r"<SNIPPET>\n?(.*?)\n?</SNIPPET>", llm_response, re.DOTALL | re.IGNORECASE
        )
        explanation = (
            thought_match.group(1).strip()
            if thought_match
            else "No explicit explanation generated."
        )
        suggested_code = snippet_match.group(1).strip() if snippet_match else ""
        suggested_code = re.sub(r"^```[a-zA-Z]*\n", "", suggested_code)
        suggested_code = re.sub(r"\n```$", "", suggested_code)
        suggested_code = suggested_code.strip()
        if not suggested_code:
            return logger.error("LLM failed to generate a valid feature snippet.")
        with open(self.feature_file, "w", encoding="utf-8") as f:
            f.write(
                f"# Feature Proposal\n\n**Target File:** `{rel_path}`\n\n**Explanation:**\n{explanation}\n\n### Suggested Addition/Optimization:\n```{lang_tag}\n{suggested_code}\n```\n\n---\n> **ACTION REQUIRED:** Review this feature proposal. Wait for terminal prompt to approve.\n"
            )
        logger.info(f"Feature proposal written to {FEATURE_FILE_NAME}.")

    def implement_feature(self, feature_content: str) -> bool:
        match = re.search(r"\*\*Target File:\*\* `(.*?)`", feature_content)
        if not match:
            logger.error("Could not determine target file from FEATURE.md formatting.")
            return False

        rel_path = match.group(1)
        target_path = os.path.join(self.target_dir, rel_path)
        target_folder = os.path.dirname(target_path)
        lang_name, lang_tag = getattr(self, "get_language_info")(target_path)

        with open(target_path, "r", encoding="utf-8") as f_handle:
            source_code = f_handle.read()

        created_files: list[str] = []
        new_file_matches = re.finditer(
            r'<CREATE_FILE path="(.*?)">(.*?)</CREATE_FILE>', feature_content, re.DOTALL
        )

        for file_match in new_file_matches:
            new_path_rel = file_match.group(1)
            new_code_payload = file_match.group(2).strip()

            # Pathing: Naked filenames go into the same package as the target file
            if "/" not in new_path_rel and "\\" not in new_path_rel:
                new_path_abs = os.path.join(target_folder, new_path_rel)
            else:
                new_path_abs = os.path.join(self.target_dir, new_path_rel)

            if not os.path.exists(new_path_abs):
                try:
                    os.makedirs(os.path.dirname(new_path_abs), exist_ok=True)
                    logger.warning(
                        f"ARCHITECTURAL SPLIT: Spawning new module `{os.path.basename(new_path_abs)}`"
                    )
                    with open(new_path_abs, "w", encoding="utf-8") as f_new:
                        f_new.write(new_code_payload)

                    # Immediately stage for Git so the Librarian sees it
                    import subprocess
                    subprocess.run(["git", "add", new_path_abs], cwd=self.target_dir)
                    created_files.append(new_path_abs)
                except Exception as e:
                    logger.error(f"Failed to create new module {new_path_rel}: {e}")

        exp_match = re.search(
            r"\*\*Explanation:\*\*(.*?)(?:###|---|>)",
            feature_content,
            re.DOTALL | re.IGNORECASE,
        )
        feature_explanation = (
            exp_match.group(1).strip()
            if exp_match
            else f"Implemented a new structural feature for: [{rel_path}]..."
        )

        logger.info(
            f"Implementing approved feature seamlessly directly into {rel_path}..."
        )
        memory_section = getattr(self, "_get_rich_context")()
        prompt = getattr(self, "load_prompt")(
            "IF.md",
            memory_section=memory_section,
            feature_content=feature_content,
            lang_name=lang_name,
            lang_tag=lang_tag,
            source_code=source_code,
            rel_path=rel_path,
        )

        new_code, _, _ = getattr(self, "get_valid_edit")(
            prompt, source_code, require_edit=True, target_filepath=target_path
        )

        if new_code == source_code:
            logger.error("Implementation failed. Rolling back created modules.")
            for file_path in created_files:
                if os.path.exists(file_path):
                    os.remove(file_path)
            return False

        if lang_tag == "python":
            new_code = getattr(self, "ensure_imports_retained")(
                source_code, new_code, target_path
            )

        with open(target_path, "w", encoding="utf-8") as f_out:
            f_out.write(new_code)

        if lang_tag == "python":
            # Verification Pipeline
            if not getattr(self, "run_linter_fix_loop")(
                context_of_change=feature_content
            ) or not getattr(self, "run_and_verify_app")(
                context_of_change=feature_content
            ):
                logger.error("Verification failed. Cleaning up spawned modules.")
                for file_path in created_files:
                    if os.path.exists(file_path):
                        os.remove(file_path)
                return False

            if not getattr(self, "check_downstream_breakages")(target_path, rel_path):
                logger.error("Downstream breakages. Rolling back spawned modules.")
                for file_path in created_files:
                    if os.path.exists(file_path):
                        os.remove(file_path)
                return False

        logger.info(f"Successfully implemented feature directly into {rel_path}.")

        self.session_context.append(
            f"SUCCESSFUL CHANGE in `{rel_path}`: {feature_explanation}"
        )

        if created_files:
            self.session_context.append(
                "Created new modules: "
                + ", ".join(
                    [os.path.basename(fp) for fp in created_files]
                )
            )

        if os.path.exists(self.feature_file):
            os.remove(self.feature_file)

        return True

    def implement_pr(self, pr_content: str) -> bool:
        """
        Implements PR patches atomically.
        Only applies changes if ALL patches in the PR pass the XML,
        safety, and verification gates.
        """
        logger.info("Implementing approved PRs seamlessly from XML blocks...")
        file_sections = re.split(r"## 🛠 Review for `(.*?)`", pr_content)

        # Guard: Ensure content actually contains patches
        if len(file_sections) < 3:
            logger.error("No valid file patches found in PR.md to apply.")
            return False

        all_success = True
        patches_to_apply = []  # Atomic transaction buffer

        # 1. PRE-FLIGHT VALIDATION (Check all patches before applying any)
        for i in range(1, len(file_sections), 2):
            rel_path = file_sections[i].strip()
            section_content = file_sections[i + 1]
            target_path = os.path.join(self.target_dir, rel_path)

            if not os.path.exists(target_path):
                logger.error(f"Target file {rel_path} not found.")
                all_success = False
                continue

            with open(target_path, "r", encoding="utf-8") as f:
                source_code = f.read()

            # Apply XML edit logic
            new_code, explanation, success = getattr(self, "apply_xml_edits")(
                source_code, section_content
            )

            # --- EMERGENCY DELETION GUARD ---
            # If the patch deletes > 50% of the file, it is highly likely a hallucination.
            if len(new_code) < (len(source_code) * 0.5):
                logger.error(
                    f"EMERGENCY STOP: Patch for {rel_path} would delete too much code."
                )
                all_success = False
                continue

            # Patch Validation
            if not success:
                logger.error(f"Failed to match XML blocks for {rel_path}.")
                all_success = False
            elif new_code == source_code:
                logger.warning(f"Patch for {rel_path} changed nothing. Skipping.")
            else:
                patches_to_apply.append((target_path, new_code, rel_path))

        # 2. ATOMIC COMMIT (Only write to disk if everything checked out)
        if all_success and patches_to_apply:
            for target_path, new_code, rel_path in patches_to_apply:
                with open(target_path, "w", encoding="utf-8") as f:
                    f.write(new_code)
                logger.info(f"Successfully applied patch to {rel_path}.")

            # 3. VERIFICATION PIPELINE (The final test)
            if not getattr(self, "run_linter_fix_loop")(
                context_of_change=pr_content
            ) or not getattr(self, "run_and_verify_app")(context_of_change=pr_content):
                logger.error("Verification failed. Changes will be rolled back.")
                return False

            self.session_context.append("Applied automated patch XML edits.")
            if os.path.exists(self.pr_file):
                os.remove(self.pr_file)
            return True

        return False
